id: I4DABB266
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:47:57.132252+00:00
last_modified: 2022-12-15 07:47:57.132263+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-060-007
  title: Toh_178-Teaching_on_the_Aids_to_Enlightenment-v2
bases:
  ACC4:
    source_metadata: null
    order: 1
    base_file: ACC4.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
